<section class="py-16 bg-white">
    <div class="container mx-auto px-4">
        <div class="max-w-4xl mx-auto">
            <!-- Title -->
            <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-8 fade-in-up">
                About Our Company
            </h2>

            <!-- Text Content -->
            <div class="space-y-6 text-gray-700 text-lg leading-relaxed mb-12 text-justify">
                <p class="fade-in-up animate-delay-100">
                    PT Intimas Surya is committed to delivering tuna products that meet high standards of freshness, safety, and consistency. Every raw material is carefully selected and inspected before entering production to ensure only the best quality reaches our customers. Through strict hygiene practices and continuous quality control, we maintain product excellence at every stage.
                </p>
                <p class="fade-in-up animate-delay-200">
                   Our processing facility is equipped with modern technology and operates under internationally recognized certifications. Each step from cutting and weighing to freezing and packaging—is handled by trained professionals who follow standardized procedures. This ensures that every batch meets global requirements for food safety and product handling.
                </p>
                <p class="fade-in-up animate-delay-300">
                    With years of experience in the seafood industry, PT Intimas Surya has become a trusted partner for markets both in Indonesia and abroad. Our commitment to quality and reliability has allowed us to build strong relationships with clients, delivering products that consistently meet their expectations. We continue to improve our processes to support long-term growth and customer satisfaction.
                </p>
            </div>

            <!-- Image Slider -->
            <div class="w-full overflow-hidden shadow-sm relative aspect-video scale-in animate-delay-400" id="about-slider">
                <div class="flex transition-transform duration-1000 ease-in-out h-full" id="slider-track">
                    <div class="w-full flex-shrink-0 h-full">
                        <img src="{{ asset('img/produksi/p1.png') }}" alt="Company Profile 1" class="w-full h-full object-cover shadow-lg rounded">
                    </div>
                    <div class="w-full flex-shrink-0 h-full">
                        <img src="{{ asset('img/produksi/p3.png') }}" alt="Company Profile 1" class="w-full h-full object-cover shadow-lg rounded">
                    </div>
                    <div class="w-full flex-shrink-0 h-full">
                        <img src="{{ asset('img/produksi/p2.png') }}" alt="Company Profile 1" class="w-full h-full object-cover shadow-lg rounded">
                    </div>
                </div>
            </div>
            
            <!-- Navigation Dots -->
            <div class="flex justify-center space-x-3 mt-4 fade-in-up animate-delay-500" id="slider-dots">
                <!-- Dots will be generated by JS -->
            </div>

            

            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    const track = document.getElementById('slider-track');
                    const slides = track.children;
                    const dotsContainer = document.getElementById('slider-dots');
                    let currentSlide = 0;
                    let intervalId;

                    // Create dots
                    for (let i = 0; i < slides.length; i++) {
                        const dot = document.createElement('button');
                        dot.className = `w-3 h-3 rounded-full transition-colors duration-300 ${i === 0 ? 'bg-[#2a3891]' : 'bg-gray-300 hover:bg-gray-400'}`;
                        dot.setAttribute('aria-label', `Go to slide ${i + 1}`);
                        dot.addEventListener('click', () => goToSlide(i));
                        dotsContainer.appendChild(dot);
                    }

                    const dots = dotsContainer.children;

                    function updateDots() {
                        for (let i = 0; i < dots.length; i++) {
                            if (i === currentSlide) {
                                dots[i].className = 'w-3 h-3 rounded-full transition-colors duration-300 bg-[#2a3891]';
                            } else {
                                dots[i].className = 'w-3 h-3 rounded-full transition-colors duration-300 bg-gray-300 hover:bg-gray-400';
                            }
                        }
                    }

                    function goToSlide(index) {
                        currentSlide = index;
                        track.style.transform = `translateX(-${currentSlide * 100}%)`;
                        updateDots();
                        resetInterval();
                    }

                    function nextSlide() {
                        currentSlide = (currentSlide + 1) % slides.length;
                        track.style.transform = `translateX(-${currentSlide * 100}%)`;
                        updateDots();
                    }

                    function resetInterval() {
                        clearInterval(intervalId);
                        intervalId = setInterval(nextSlide, 4000);
                    }

                    // Start auto-slide
                    intervalId = setInterval(nextSlide, 4000);
                });
            </script>
        </div>
    </div>
</section>
