<section class="py-16 bg-white">
    <div class="container mx-auto px-4">
        <div class="max-w-4xl mx-auto">
            <!-- Title -->
            <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-8 fade-in-up">
                Quality & Responsibility
            </h2>

            <!-- Text Content -->
            <div class="space-y-6 text-gray-700 text-lg leading-relaxed mb-12 text-justify">
                <p class="fade-in-up animate-delay-100">
                   We ensure every step of our tuna production follows strict safety, hygiene, and handling standards, from the moment the fish is sourced until it reaches final processing. Our team follows disciplined workflows, detailed inspections, and consistent monitoring to maintain product freshness and reliability. With responsible practices and continuous quality control, we deliver tuna that meets international expectations while supporting ethical and transparent operations.
            </div>

            <!-- Image Slider -->
            <div class="w-full overflow-hidden shadow-sm relative aspect-video scale-in animate-delay-200" id="about-slider">
                <div class="flex transition-transform duration-1000 ease-in-out h-full" id="slider-track">
                    <div class="w-full flex-shrink-0 h-full">
                        <img src="{{ asset('img/produksi/p1.png') }}" alt="Company Profile 1" class="w-full h-full object-cover shadow-lg rounded">
                    </div>
                    <div class="w-full flex-shrink-0 h-full">
                        <img src="{{ asset('img/produksi/p2.png') }}" alt="Company Profile 1" class="w-full h-full object-cover shadow-lg rounded">
                    </div>
                    <div class="w-full flex-shrink-0 h-full">
                        <img src="{{ asset('img/produksi/p3.png') }}" alt="Company Profile 1" class="w-full h-full object-cover shadow-lg rounded">
                    </div>
                </div>
            </div>
            
            <!-- Navigation Dots -->
            <div class="flex justify-center space-x-3 mt-4 fade-in-up animate-delay-300" id="slider-dots">
                <!-- Dots will be generated by JS -->
            </div>

            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    const track = document.getElementById('slider-track');
                    const slides = track.children;
                    const dotsContainer = document.getElementById('slider-dots');
                    let currentSlide = 0;
                    let intervalId;

                    // Create dots
                    for (let i = 0; i < slides.length; i++) {
                        const dot = document.createElement('button');
                        dot.className = `w-3 h-3 rounded-full transition-colors duration-300 ${i === 0 ? 'bg-[#2a3891]' : 'bg-gray-300 hover:bg-gray-400'}`;
                        dot.setAttribute('aria-label', `Go to slide ${i + 1}`);
                        dot.addEventListener('click', () => goToSlide(i));
                        dotsContainer.appendChild(dot);
                    }

                    const dots = dotsContainer.children;

                    function updateDots() {
                        for (let i = 0; i < dots.length; i++) {
                            if (i === currentSlide) {
                                dots[i].className = 'w-3 h-3 rounded-full transition-colors duration-300 bg-[#2a3891]';
                            } else {
                                dots[i].className = 'w-3 h-3 rounded-full transition-colors duration-300 bg-gray-300 hover:bg-gray-400';
                            }
                        }
                    }

                    function goToSlide(index) {
                        currentSlide = index;
                        track.style.transform = `translateX(-${currentSlide * 100}%)`;
                        updateDots();
                        resetInterval();
                    }

                    function nextSlide() {
                        currentSlide = (currentSlide + 1) % slides.length;
                        track.style.transform = `translateX(-${currentSlide * 100}%)`;
                        updateDots();
                    }

                    function resetInterval() {
                        clearInterval(intervalId);
                        intervalId = setInterval(nextSlide, 4000);
                    }

                    // Start auto-slide
                    intervalId = setInterval(nextSlide, 4000);
                });
            </script>
        </div>
    </div>
</section>
